version: 2.0

quay_io_login: &quay_io_login
  name: Login to Quay.io register
  command: docker login quay.io -u "${QUAY_USER}" -p "${QUAY_TOKEN}"

# every token of the docker image name has to be lowercase
# ${variable,,} is a Bash 4 syntax to lowercase a variable.
docker_image_name: &docker_image_name
  name: Set DOCKER_IMAGE_NAME env variable
  command: |
    echo 'export DOCKER_IMAGE_NAME="quay.io/${CIRCLE_PROJECT_USERNAME,,}/${CIRCLE_PROJECT_REPONAME,,}:${CIRCLE_TAG}"' >> $BASH_ENV
    source $BASH_ENV

jobs:
  Odoo:
    machine: true
    steps:
       - checkout
       - run:
           <<: *quay_io_login
       - run:
          name: Docker Build
          command: docker-compose build
       - run:
          name: Init Database
          command: docker-compose run --rm odoo odoo --stop-after-init -i client
       - run:
          name: Run Javascript Tests
          command: docker-compose run --rm client npm test
       - store_test_results:
          path: ./log

  deploy:
    machine: true
    steps:
       - checkout
       - run:
           <<: *quay_io_login
       - run:
           <<: *docker_image_name

       - run:
           name: Docker build
           command: docker build --build-arg GIT_TOKEN=${GIT_TOKEN}  --rm --pull -t "${DOCKER_IMAGE_NAME}" .

       - run:
           name: Docker push
           command: docker push "${DOCKER_IMAGE_NAME}"

  # job that find the next tag for the current branch/repo and push the tag to github.
  # it will trigger the publish of a new docker image.
  auto-tag:
    machine: true
    steps:
      - checkout
      - run:
          name: Get next tag
          command: |
            echo 'export GITHUB_NEXT_TAG=$(curl -fL http://gcloud.functions.numigi.org/github_next_tag?github_user=${GITHUB_USER}\&github_password=${GITHUB_PASSWORD}\&repo=${CIRCLE_PROJECT_REPONAME}\&filter=${CIRCLE_BRANCH/\.0/})' > $BASH_ENV
            source $BASH_ENV
            echo github next tag: ${GITHUB_NEXT_TAG}
      - run:
          name: Create tag
          command: |
            echo repo: ${CIRCLE_PROJECT_REPONAME}
            echo branch: ${CIRCLE_BRANCH}
            echo tag: ${GITHUB_NEXT_TAG}
            echo github_create_tag $(curl -fL http://gcloud.functions.numigi.org/github_create_tag?github_user=${GITHUB_USER}\&github_password=${GITHUB_PASSWORD}\&repo=${CIRCLE_PROJECT_REPONAME}\&branch=${CIRCLE_BRANCH}\&tag=${GITHUB_NEXT_TAG})

# Quay.io autobuild are not compatible with build args
# see https://isidor-prod.numigi.net/web#id=1663&view_type=form&model=project.task&action=298&menu_id=200
workflows:
  version: 2
  build:
    jobs:
      - Odoo:
          context: quay.io
          filters:
            tags:
              ignore: /.*/

      - deploy:
          context: quay.io
          filters:
            tags:
              only: /[0-9]+(\.[0-9]+)*/
            branches:
              ignore: /.*/

      - auto-tag:
          context: github-robot
          requires:
            - Odoo
          filters:
            branches:
              only: /^1\d\.0/
