jobs:
  odoo:
    machine: true
    steps:
       - checkout

       - run:
          name: Login to Quay.io
          command: docker login quay.io -u "${QUAY_USER}" -p "${QUAY_TOKEN}"

       - run:
          name: Build -- Init Database
          command: docker-compose run --rm odoo odoo --stop-after-init -i main

       - run:
          name: Run Javascript Tests
          command: docker-compose run --rm client npm test

       - store_test_results:
          path: .log

workflows:
  version: 2
  basic-odoo-test:
    jobs:
      - odoo:
          context: quay.io